# Generated by Django 4.1.2 on 2022-10-10 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_cours_eleve_info_matiere_alter_user_role_professeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
