# Generated by Django 4.1.2 on 2022-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_note_eleve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Cour',
        ),
    ]
