# Generated by Django 4.1.2 on 2022-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_cours_cour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='I',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='I2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='I2content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='I3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='I3content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='Icontent',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='conclusion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='intro',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
