# Generated by Django 4.1.2 on 2022-10-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_cour_i_cour_i2_cour_i2content_cour_i3_cour_i3content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cour',
            name='I',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='I2',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='I2content',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='I3',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='I3content',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='Icontent',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='intro',
        ),
    ]
