# Generated by Django 4.1.2 on 2022-11-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_info_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('Telephone', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='etablissement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.etablissement'),
        ),
    ]
