# Generated by Django 4.1.2 on 2022-11-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_etablissement_eleve_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.etablissement'),
        ),
    ]
