# Generated by Django 4.1.2 on 2022-11-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='matiere',
            new_name='devoir',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='note',
        ),
    ]
