# Generated by Django 4.1.2 on 2022-11-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_rename_matiere_note_devoir_remove_devoir_eleve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='devoir',
            new_name='matiere',
        ),
    ]
