# Generated by Django 4.1.2 on 2023-02-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_rename_devoir_note_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='valeur',
        ),
    ]
