# Generated by Django 4.1.2 on 2023-02-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_rename_note_note_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='note',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
